theme: jekyll-theme-slate
title: Genwakan 厳和館 dojo in Alameda and Emeryville, California
description: Muso Jikiden Eishin Ryu Iaido classes for adults and youth in Alameda and Emeryville. We are anofficial dojo of World MJER Iaido Federation 正統正流無雙直傳英信流居合道国際連盟
